//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Desktop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Desktop() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Desktop", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo sinh nhật.
        /// </summary>
        internal static string birthdays_staff {
            get {
                return ResourceManager.GetString("birthdays_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu đồ.
        /// </summary>
        internal static string chart {
            get {
                return ResourceManager.GetString("chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo độ tuổi.
        /// </summary>
        internal static string chart_by_age {
            get {
                return ResourceManager.GetString("chart_by_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo tỉnh thành.
        /// </summary>
        internal static string chart_by_city {
            get {
                return ResourceManager.GetString("chart_by_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo loại hợp đồng.
        /// </summary>
        internal static string chart_by_contract_type {
            get {
                return ResourceManager.GetString("chart_by_contract_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo dân tộc.
        /// </summary>
        internal static string chart_by_ethnicity {
            get {
                return ResourceManager.GetString("chart_by_ethnicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu đồ biến động CBCC.
        /// </summary>
        internal static string chart_by_fluctuation {
            get {
                return ResourceManager.GetString("chart_by_fluctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo giới tính.
        /// </summary>
        internal static string chart_by_gender {
            get {
                return ResourceManager.GetString("chart_by_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê theo thâm niên công tác.
        /// </summary>
        internal static string chart_by_length_of_service {
            get {
                return ResourceManager.GetString("chart_by_length_of_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo trình độ.
        /// </summary>
        internal static string chart_by_level {
            get {
                return ResourceManager.GetString("chart_by_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo tình trạng hôn nhân.
        /// </summary>
        internal static string chart_by_marriage_status {
            get {
                return ResourceManager.GetString("chart_by_marriage_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo cấp bậc quân đội.
        /// </summary>
        internal static string chart_by_military_grade {
            get {
                return ResourceManager.GetString("chart_by_military_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo quốc tịch.
        /// </summary>
        internal static string chart_by_natinonality {
            get {
                return ResourceManager.GetString("chart_by_natinonality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo chức vụ đảng.
        /// </summary>
        internal static string chart_by_party_office {
            get {
                return ResourceManager.GetString("chart_by_party_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo tôn giáo.
        /// </summary>
        internal static string chart_by_religion {
            get {
                return ResourceManager.GetString("chart_by_religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo bộ phận.
        /// </summary>
        internal static string chart_by_section {
            get {
                return ResourceManager.GetString("chart_by_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo chức vụ đoàn.
        /// </summary>
        internal static string chart_by_union_office {
            get {
                return ResourceManager.GetString("chart_by_union_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê CBCC theo đơn vị.
        /// </summary>
        internal static string chart_by_unit {
            get {
                return ResourceManager.GetString("chart_by_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu đồ mở rộng.
        /// </summary>
        internal static string chart_expand {
            get {
                return ResourceManager.GetString("chart_expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn đặt biểu đồ này làm mặc định?.
        /// </summary>
        internal static string confirm_set_default {
            get {
                return ResourceManager.GetString("confirm_set_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thông tin về địa chỉ mail của nhân viên.
        /// </summary>
        internal static string email_not_found {
            get {
                return ResourceManager.GetString("email_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã cán bộ hoặc họ tên.
        /// </summary>
        internal static string enter_code_or_name {
            get {
                return ResourceManager.GetString("enter_code_or_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở rộng.
        /// </summary>
        internal static string expansion {
            get {
                return ResourceManager.GetString("expansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        internal static string expiration_date {
            get {
                return ResourceManager.GetString("expiration_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thể tìm kiếm theo mã cán bộ, họ tên(có thể không cần dấu tiếng việt), số điện thoại, số CMT hoặc địa chỉ email.
        /// </summary>
        internal static string guild_search_desktop {
            get {
                return ResourceManager.GetString("guild_search_desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng chấm công.
        /// </summary>
        internal static string labour_table {
            get {
                return ResourceManager.GetString("labour_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn bảng chấm công.
        /// </summary>
        internal static string no_select_labour_table {
            get {
                return ResourceManager.GetString("no_select_labour_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán bộ sắp hết hạn hợp đồng.
        /// </summary>
        internal static string out_of_contract {
            get {
                return ResourceManager.GetString("out_of_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In danh sách.
        /// </summary>
        internal static string print_list {
            get {
                return ResourceManager.GetString("print_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo danh sách cán bộ sinh nhật trong tháng.
        /// </summary>
        internal static string report_staff_birthday {
            get {
                return ResourceManager.GetString("report_staff_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo hồ sơ cán bộ.
        /// </summary>
        internal static string report_staff_profile {
            get {
                return ResourceManager.GetString("report_staff_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra cứu nhanh thông tin CBCCVC.
        /// </summary>
        internal static string search_quick_staff_info {
            get {
                return ResourceManager.GetString("search_quick_staff_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn bảng chấm công.
        /// </summary>
        internal static string select_labour_table {
            get {
                return ResourceManager.GetString("select_labour_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn lấy một cán bộ sau đó ấn báo cáo để in ra thông tin cá nhân.
        /// </summary>
        internal static string select_staff_and_report {
            get {
                return ResourceManager.GetString("select_staff_and_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn loại biểu đồ.
        /// </summary>
        internal static string select_type_of_chart {
            get {
                return ResourceManager.GetString("select_type_of_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn năm.
        /// </summary>
        internal static string select_year {
            get {
                return ResourceManager.GetString("select_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt làm biểu đồ mặc định.
        /// </summary>
        internal static string set_default_chart {
            get {
                return ResourceManager.GetString("set_default_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ký.
        /// </summary>
        internal static string signing_date {
            get {
                return ResourceManager.GetString("signing_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán bộ.
        /// </summary>
        internal static string staff {
            get {
                return ResourceManager.GetString("staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ vào.
        /// </summary>
        internal static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký hiệu.
        /// </summary>
        internal static string symbol {
            get {
                return ResourceManager.GetString("symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công cụ.
        /// </summary>
        internal static string tool {
            get {
                return ResourceManager.GetString("tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bấm vào đây để xem toàn màn hình.
        /// </summary>
        internal static string view_fullscreen {
            get {
                return ResourceManager.GetString("view_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng làm việc.
        /// </summary>
        internal static string working_status {
            get {
                return ResourceManager.GetString("working_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng làm việc.
        /// </summary>
        internal static string work_status {
            get {
                return ResourceManager.GetString("work_status", resourceCulture);
            }
        }
    }
}
