//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HOSO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HOSO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HOSO", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa không ?.
        /// </summary>
        internal static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.Tài sản cấp phát.
        /// </summary>
        internal static string Asset_Allocation {
            get {
                return ResourceManager.GetString("Asset_Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng lại.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hợp đồng.
        /// </summary>
        internal static string contract_type {
            get {
                return ResourceManager.GetString("contract_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thử việc.
        /// </summary>
        internal static string day_probation {
            get {
                return ResourceManager.GetString("day_probation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} đến dòng {1} / {2} dòng.
        /// </summary>
        internal static string description_record {
            get {
                return ResourceManager.GetString("description_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân đôi dữ liệu.
        /// </summary>
        internal static string Double_data {
            get {
                return ResourceManager.GetString("Double_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email nội bộ.
        /// </summary>
        internal static string EmailNoiBo {
            get {
                return ResourceManager.GetString("EmailNoiBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ Excel.
        /// </summary>
        internal static string enter_from_excel {
            get {
                return ResourceManager.GetString("enter_from_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang đầu tiên.
        /// </summary>
        internal static string first_page {
            get {
                return ResourceManager.GetString("first_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng tệp tin không hợp lệ.
        /// </summary>
        internal static string Formats_file_is_not_valid {
            get {
                return ResourceManager.GetString("Formats_file_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cơ bản.
        /// </summary>
        internal static string general_information {
            get {
                return ResourceManager.GetString("general_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        internal static string guide {
            get {
                return ResourceManager.GetString("guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ nhân sự.
        /// </summary>
        internal static string HR_profile {
            get {
                return ResourceManager.GetString("HR_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMT.
        /// </summary>
        internal static string identity_number {
            get {
                return ResourceManager.GetString("identity_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Hợp đồng lao động.
        /// </summary>
        internal static string Labour_Contract {
            get {
                return ResourceManager.GetString("Labour_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cuối cùng.
        /// </summary>
        internal static string last_page {
            get {
                return ResourceManager.GetString("last_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải dữ liệu.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã CBNV&lt;span style=&apos;color:red;&apos;&gt;*&lt;/span&gt;.
        /// </summary>
        internal static string MaCanBo {
            get {
                return ResourceManager.GetString("MaCanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật ảnh hàng loạt.
        /// </summary>
        internal static string mass_update_image {
            get {
                return ResourceManager.GetString("mass_update_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ được nhập tối đa 50 ký tự.
        /// </summary>
        internal static string maximum_characters {
            get {
                return ResourceManager.GetString("maximum_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang sau.
        /// </summary>
        internal static string next_page {
            get {
                return ResourceManager.GetString("next_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string notify {
            get {
                return ResourceManager.GetString("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện không có dữ liệu.
        /// </summary>
        internal static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn bản ghi nào.
        /// </summary>
        internal static string no_selected_record {
            get {
                return ResourceManager.GetString("no_selected_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dòng trên một trang:.
        /// </summary>
        internal static string number_line_per_page {
            get {
                return ResourceManager.GetString("number_line_per_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhận chính thức.
        /// </summary>
        internal static string official_day {
            get {
                return ResourceManager.GetString("official_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dòng trên 1 trang.
        /// </summary>
        internal static string page_size {
            get {
                return ResourceManager.GetString("page_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        internal static string personal_information {
            get {
                return ResourceManager.GetString("personal_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ trong giây lát.
        /// </summary>
        internal static string Please_wait {
            get {
                return ResourceManager.GetString("Please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang trước.
        /// </summary>
        internal static string prev_page {
            get {
                return ResourceManager.GetString("prev_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Thông tin hồ sơ.
        /// </summary>
        internal static string Profile_information {
            get {
                return ResourceManager.GetString("Profile_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo.
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ảnh.
        /// </summary>
        internal static string Select_Image {
            get {
                return ResourceManager.GetString("Select_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phần mềm chỉ chấp nhận các định dạng ảnh jpg, png, gif, bmp, jpeg!.
        /// </summary>
        internal static string software_only_accept_image {
            get {
                return ResourceManager.GetString("software_only_accept_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu cán bộ, công chức.
        /// </summary>
        internal static string SoHieuCanBo {
            get {
                return ResourceManager.GetString("SoHieuCanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày học việc.
        /// </summary>
        internal static string SoNgayHocViec {
            get {
                return ResourceManager.GetString("SoNgayHocViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string staff_address {
            get {
                return ResourceManager.GetString("staff_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;3) Sinh ngày&lt;/b&gt;.
        /// </summary>
        internal static string staff_birthday {
            get {
                return ResourceManager.GetString("staff_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;3) Ngày sinh&lt;/b&gt;&lt;span style=&apos;color:red;&apos;&gt;*&lt;/span&gt;.
        /// </summary>
        internal static string staff_birthday_required {
            get {
                return ResourceManager.GetString("staff_birthday_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã CB.
        /// </summary>
        internal static string staff_code {
            get {
                return ResourceManager.GetString("staff_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Giới tính&lt;/b&gt;.
        /// </summary>
        internal static string staff_gender {
            get {
                return ResourceManager.GetString("staff_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ.
        /// </summary>
        internal static string staff_level {
            get {
                return ResourceManager.GetString("staff_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string staff_name {
            get {
                return ResourceManager.GetString("staff_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;1) Họ và tên khai sinh&lt;/b&gt;&lt;span style=&apos;color:red;&apos;&gt;*&lt;/span&gt;.
        /// </summary>
        internal static string staff_name_required {
            get {
                return ResourceManager.GetString("staff_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string staff_phone {
            get {
                return ResourceManager.GetString("staff_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        internal static string staff_section {
            get {
                return ResourceManager.GetString("staff_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian thử việc.
        /// </summary>
        internal static string ThoiGianThuViec {
            get {
                return ResourceManager.GetString("ThoiGianThuViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường đào tạo.
        /// </summary>
        internal static string training_school {
            get {
                return ResourceManager.GetString("training_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiện ích.
        /// </summary>
        internal static string utility {
            get {
                return ResourceManager.GetString("utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
